import problems.leetcode.das.hashing.HashingContinousArray
import problems.leetcode.das.hashing.HashingMaximumNumberOfBalloons

fun main() {
    //ProblemTwoSums().execute()
    //ProblemContainerWithMostWater().execute()
    //ProblemTrappingRainWater().execute()
    //ProblemReverseString().execute()
    //ProblemSquaresOfSortedArray().execute()
    //Example1().execute()
    //Example2().execute()
    //Example3().execute()
    //Example4().execute()
    //ProblemMaximumAverageSubarray().execute()
    //ProblemMaxConsecutiveOnesIII().execute()
    //Example1().execute()
    //Example2().execute()
    //ProblemSumOf1dArray().execute()
    //ProblemMinimumValueToGetPositiveStepByStepSum().execute()
    //ProblemKRadiusSubarrayAverages().execute()
    //TwoPointersReverseWordsInAStringIII().execute()
    //CheckingForExistenceExample2LetterToAppearTwice().execute()
    //CheckingForExistenceExample3UniqueNumbers().execute()
    //HashingCheckifSentenceIsPangram().execute()
    //HashingMissingNumber().execute()
    //HashingCountingNumbers().execute()
    //CountingExample1().execute()
    //CountingExample2().execute()
    //CountingExample3().execute()
    //CountingExample4().execute()
    //CountingExample5().execute()
    //HashingFindPlayersWithZeroOrOneLosses().execute()
    //HashingLargestUniqueNumber().execute()
    //HashingMaximumNumberOfBalloons().execute()
    HashingContinousArray().execute()
}
